### ISSUE TITLE
[Bug]: lunar-phase-card doesn't work with expander-card

### ISSUE THREAD

**Issue by TheDjGogo2000** [ngocjohn/lunar-phase-card#68]
### Short summary 📝

lunar goes wrong when use expander-card

### Detailed description 📋

Hi, when i use lunar-phase-card as a child of expander-card, only the title appear

My code to reproduce the bug : 

> - type: custom:expander-card

            clear: false
            clear-children: false
            title: Lune
            button-background: transparent
            cards:
              - type: custom:lunar-phase-card
                entity: ""
                12hr_format: false
                calendar_modal: false
                compact_view: false
                default_card: base
                hide_buttons: false
                mile_unit: false
                moon_position: left
                number_decimals: 2
                selected_language: fr
                show_background: true
                southern_hemisphere: false
                use_custom: false
                use_default: true
                use_entity: false
                graph_config:
                  graph_type: default
                  y_ticks: false
                  x_ticks: false
                  show_time: true
                  show_current: true
                  show_highest: true
                  y_ticks_position: left
                  y_ticks_step_size: 30
                  time_step_size: 30
                font_customize:
                  header_font_size: x-large
                  header_font_style: capitalize
                  header_font_color: ""
                  label_font_size: auto
                  label_font_style: none
                  label_font_color: ""
                  hide_label: false
                latitude: 47.47298563023217
                longitude: 6.026682235880899
                location:
                  city: ""
                  country: France`

### Version 📦

v1.10.0

### Card Configuration

```yaml
type: custom:lunar-phase-card
                entity: ""
                12hr_format: false
                calendar_modal: false
                compact_view: false
                default_card: base
                hide_buttons: false
                mile_unit: false
                moon_position: left
                number_decimals: 2
                selected_language: fr
                show_background: true
                southern_hemisphere: false
                use_custom: false
                use_default: true
                use_entity: false
                graph_config:
                  graph_type: default
                  y_ticks: false
                  x_ticks: false
                  show_time: true
                  show_current: true
                  show_highest: true
                  y_ticks_position: left
                  y_ticks_step_size: 30
                  time_step_size: 30
                font_customize:
                  header_font_size: x-large
                  header_font_style: capitalize
                  header_font_color: ""
                  label_font_size: auto
                  label_font_style: none
                  label_font_color: ""
                  hide_label: false
                latitude: 47.47298563023217
                longitude: 6.026682235880899
                location:
                  city: ""
                  country: France
```

### Environment 🌐

Android, Win10
